name: Build OFRP

on:
  workflow_dispatch:

jobs:
  build:

    name: 🦊 Build OrangeFox Recovery
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print default env
      run: env

    - name: Build
      uses: linastorvaldz/orangefox-builder-action@master
      with:
        FOX_SYNC_BRANCH: 12.1
        DEVICE_TREE: https://github.com/a4lippp/android_recovery_samsung_m15x.git
        DEVICE_TREE_BRANCH: android-12.1
        DEVICE_PATH: device/samsung/m15x
        DEVICE_NAME: m15x
        BUILD_TARGET: recovery
        TG_CHAT_ID: ${{ secrets.CHAT_ID }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
