name: Build TWRP [tanzanite]

on:
  workflow_dispatch:

jobs:
  build:

    name: Build TWRP Recovery
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print default env
      run: env

    - name: Build
      uses: imnathanzero/cusrec-builder-action@master
      with:
        USER_NAME: imnathanzero
        USER_EMAIL: nathannxx@proton.me
        TWRP_SYNC_BRANCH: 12.1
        DEVICE_TREE: https://github.com/Mayuri-Chan/recovery_device_xiaomi_tanzanite
        DEVICE_TREE_BRANCH: 12.1
        DEVICE_PATH: device/xiaomi/tanzanite
        DEVICE_NAME: tanzanite
        BUILD_TARGET: vendorboot
        TG_CHAT_ID: ${{ secrets.CHAT_ID }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
